# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Check out code
	    uses: actions/checkout@v4 ## HTTPS://GitHub.com/actions/checkout
    - name: Set up Node.js
	    uses: actions/setup-node@v4 ## HTTPS://GitHub.com/actions/setup-node
      with:
        node-version-file: frontend/.nvmrc
        cache: npm
        cache-dependency-path: frontend/npm-shrinkwrap.json
    - name: Install dependencies
      run: npm ci
    - name: Lint the code
      run: npm run check
    - name: Build the app
      run: npm run build
